name: ci

on:
    push:
        branches:
        - pr2
    pull_request:
        branches:
        - pr2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: pr2

        - name: Install
          run: |
            sudo apt update
            sudo apt-get install -y g++ make debhelper dpkg-dev
            sudo apt-get install -y catch2 build-essential cmake
            git clone https://github.com/catchorg/Catch2.git
            cd Catch2
            
            mkdir build
            cd build
            cmake .. -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
            make
            sudo make install
            
            echo "-------------------------"
            echo " pwd:"
            pwd
            echo "-------------------------"
            echo "ls:"
            ls
            cd ..
            echo "-------------------------"
            echo "ls ..:"
            ls
            echo "-------------------------"
            echo "catch2:"
            dpkg -L catch2
            echo "-------------------------"
            echo "catch2_header:"
            cd /usr/include/catch2
            ls
            echo "-------------------------"
            echo "/usr/lib:"
            cd /usr/lib
            ls
            echo "-------------------------"
            echo "lib:"
            cd /lib
            ls

           

        - name: Build
          run: |
            echo "-------------------------"
            echo "build:"
            echo "-------------------------"
            ls
            cd src
            make -f Makefile all

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Test
          run: |
            make -f Makefile clean
            make -f Makefile test

    package:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:
        - name: Build package
          run:  |
            make -f Makefile package
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: build-package
            path: ./usr/bin/isPrime.deb
