name: ci

on:
    push:
        branches:
        - pr2
    pull_request:
        branches:
        - pr2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: pr2

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ make debhelper dpkg-dev
            sudo apt-get install -y git build-essential cmake

        - name: Install Catch2
          run: |
            git clone https://github.com/catchorg/Catch2.git
            cd Catch2
            
            mkdir build
            cd build
            cmake .. -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
            make
            sudo make install
            
            cd ../..
            rm -rf Catch2
          
        - name: Create testlib
          run: |
            mkdir testlib
            cd testlib
            mkdir lib
            mkdir include
            cp /usr/local/lib/libCatch2.a lib/libCatch2.a
            cp /usr/local/lib/libCatch2Main.a lib/libCatch2Main.a
            cp -r /usr/local/include/catch2 include
            cd ..

        - name: Build
          run: |
            cd src
            make build
        
        - name: Save testlib artifact
          uses: actions/upload-artifact@v4
          with:
            name: testlib
            path: testlib/

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: pr2

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ make debhelper dpkg-dev
 
        - name: Download testlib artifact
          uses: actions/download-artifact@v4
          with:
            name: testlib
            path: testlib/


        - name: Test
          run: |
            cd src
            make clean
            make test

        - name: Save test result artifact
          uses: actions/upload-artifact@v4
          with:
            name: bin
            path: usr/bin/

    package:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: pr2

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ make debhelper dpkg-dev

        - name: Download testlib artifact
          uses: actions/download-artifact@v4
          with:
            name: bin
            path: usr/bin/

        - name: Build package
          run:  |
            cd src
            make package
            cd ..

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: deb-package
            path: usr/bin/isPrime.deb
