name: ci

on:
    push:
        branches:
        - pr2
    pull_request:
        branches:
        - pr2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: pr2

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ make debhelper dpkg-dev
            sudo apt-get install -y catch2 build-essential cmake

        - name: Install Catch2
          run: |
            git clone https://github.com/catchorg/Catch2.git
            cd Catch2
            
            mkdir build
            cd build
            cmake .. -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
            make
            sudo make install
            
            cd ../..
            rm -rf Catch2
          
        - name: Create testlib
          run: |
            mkdir testlib
            cd testlib
            mkdir lib
            mkdir include
            cp /usr/local/lib/libCatch2.a lib/libCatch2Main.a
            cp /usr/local/lib/libCatch2Main.a lib/libCatch2Main.a
            cp /usr/local/include/catch2/catch_all.hpp include/catch2/catch_all.hpp
            cd ..

            echo "-------------------------"
            echo " pwd:"
            pwd
            echo "-------------------------"
            echo "ls:"
            ls
            cd ..
            echo "-------------------------"
            echo "ls ..:"
            ls
            echo "-------------------------"
            echo "catch2:"
            dpkg -L catch2
            echo "-------------------------"
            echo "catch2_header:"
            cd /usr/include/catch2
            ls
            echo "-------------------------"
            echo "/usr/lib:"
            cd /usr/lib
            ls
            echo "-------------------------"
            echo "lib:"
            cd /lib
            ls

           

        - name: Build
          run: |
            echo "-------------------------"
            echo "build:"
            echo "-------------------------"
            ls
            cd src
            make all
        
        - name: Save testlib artifact
          uses: actions/upload-artifact@v4
          with:
            name: build-artifact
            path: testlib/

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: pr2

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ make debhelper dpkg-dev
 
        - name: Download testlib artifact
          uses: actions/download-artifact@v4
          with:
            name: build-artifact
            path: testlib/


        - name: Test
          run: |
            echo "-------------------------"
            echo "test:"
            echo "-------------------------"
            ls
            echo "-------------------------"
            cd testlib
            echo "-------------------------"
            echo "testlib:"
            echo "-------------------------"
            ls
            echo "-------------------------"
            cd include
            echo "-------------------------"
            echo "testlib/include:"
            echo "-------------------------"
            ls
            echo "-------------------------"
            cd ../..
            cd src
            make clean
            make test

        - name: Save test result artifact
          uses: actions/upload-artifact@v4
          with:
            name: test-artifact
            path: usr/bin/

    package:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: pr2

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++ make debhelper dpkg-dev

        - name: Download testlib artifact
          uses: actions/download-artifact@v4
          with:
            name: test-artifact
            path: usr/bin/

        - name: Build package
          run:  |
            cd src
            make package
            cd ..

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: deb-package
            path: usr/bin/isPrime.deb
